# Generated by Django 2.0.2 on 2019-12-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=150)),
                ('face_id', models.IntegerField()),
            ],
        ),
    ]
