# Generated by Django 2.0.2 on 2019-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face',
            name='id',
        ),
        migrations.AlterField(
            model_name='face',
            name='face_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
